package com.officeai.triprequest.model;

import org.kie.api.definition.type.Label;

import java.util.ArrayList;
import java.util.Date;

/**
 * This class was automatically generated by the data modeler tool.
 */
public class ExportDocument implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @Label(value = "tripClassNew")
    private java.lang.String 出張分類;
    @Label(value = "fundClass")
    private java.lang.String 資金種別;
    @Label(value = "startDate")
    private Date 開始日;
    @Label(value = "endDate")
    private Date 終了日;
    @Label(value = "destinationAndReason")
    private java.lang.String 用務先事由;
    @Label(value = "teikiStart")
    private java.lang.String 定期始点;
    @Label(value = "teikiEnd")
    private java.lang.String 定期終点;
    @Label(value = "businessPersonBelong")
    private java.lang.String 事業担当者所属;
    @Label(value = "businessPersonStaffNumber")
    private java.lang.String 事業担当者教職員番号;
    @Label(value = "businessPersonJobTitle")
    private java.lang.String 事業担当者職種;
    @Label(value = "businessPersonName")
    private java.lang.String 事業担当者氏名;
    @Label(value = "businessPersonExtension")
    private java.lang.String 事業担当者連絡先;
    @Label(value = "businessTravelerBelong")
    private java.lang.String 出張者所属;
    @Label(value = "businessTravelerStaffNumber")
    private java.lang.String 出張者教職員番号;
    @Label(value = "businessTravelerJobTitle")
    private java.lang.String 出張者職種;
    @Label(value = "businessTravelerName")
    private java.lang.String 出張者氏名;
    @Label(value = "businessTravelerExtension")
    private java.lang.String 出張者連絡先;
    @Label(value = "resultData")
    private ArrayList<Result> 結果;
    @Label(value = "getOnPlane")
    private java.lang.Boolean 航空機を利用するか;
    @Label(value = "getOnTrain")
    private java.lang.Boolean 電車を利用するか;
    @Label(value = "remarks")
    private java.lang.String 備考;

    public ExportDocument() {
    }

    public java.lang.String get出張分類() {
        return this.出張分類;
    }

    public void set出張分類(java.lang.String 出張分類) {
        this.出張分類 = 出張分類;
    }

    public java.lang.String get資金種別() {
        return this.資金種別;
    }

    public void set資金種別(java.lang.String 資金種別) {
        this.資金種別 = 資金種別;
    }

    public Date get開始日() {
        return this.開始日;
    }

    public void set開始日(Date 開始日) {
        this.開始日 = 開始日;
    }

    public Date get終了日() {
        return this.終了日;
    }

    public void set終了日(Date 終了日) {
        this.終了日 = 終了日;
    }

    public java.lang.String get用務先事由() {
        return this.用務先事由;
    }

    public void set用務先事由(java.lang.String 用務先事由) {
        this.用務先事由 = 用務先事由;
    }

    public java.lang.String get事業担当者所属() {
        return this.事業担当者所属;
    }

    public java.lang.String get定期始点() {
        return this.定期始点;
    }

    public void set定期始点(java.lang.String 定期始点) {
        this.定期始点 = 定期始点;
    }

    public java.lang.String get定期終点() {
        return this.定期終点;
    }

    public void set定期終点(java.lang.String 定期終点) {
        this.定期終点 = 定期終点;
    }

    public void set事業担当者所属(java.lang.String 事業担当者所属) {
        this.事業担当者所属 = 事業担当者所属;
    }

    public java.lang.String get事業担当者教職員番号() {
        return this.事業担当者教職員番号;
    }

    public void set事業担当者教職員番号(java.lang.String 事業担当者教職員番号) {
        this.事業担当者教職員番号 = 事業担当者教職員番号;
    }

    public java.lang.String get事業担当者職種() {
        return this.事業担当者職種;
    }

    public void set事業担当者職種(java.lang.String 事業担当者職種) {
        this.事業担当者職種 = 事業担当者職種;
    }

    public java.lang.String get事業担当者氏名() {
        return this.事業担当者氏名;
    }

    public void set事業担当者氏名(java.lang.String 事業担当者氏名) {
        this.事業担当者氏名 = 事業担当者氏名;
    }

    public java.lang.String get事業担当者連絡先() {
        return this.事業担当者連絡先;
    }

    public void set事業担当者連絡先(java.lang.String 事業担当者連絡先) {
        this.事業担当者連絡先 = 事業担当者連絡先;
    }

    public java.lang.String get出張者所属() {
        return this.出張者所属;
    }

    public void set出張者所属(java.lang.String 出張者所属) {
        this.出張者所属 = 出張者所属;
    }

    public java.lang.String get出張者教職員番号() {
        return this.出張者教職員番号;
    }

    public void set出張者教職員番号(java.lang.String 出張者教職員番号) {
        this.出張者教職員番号 = 出張者教職員番号;
    }

    public java.lang.String get出張者職種() {
        return this.出張者職種;
    }

    public void set出張者職種(java.lang.String 出張者職種) {
        this.出張者職種 = 出張者職種;
    }

    public java.lang.String get出張者氏名() {
        return this.出張者氏名;
    }

    public void set出張者氏名(java.lang.String 出張者氏名) {
        this.出張者氏名 = 出張者氏名;
    }

    public java.lang.String get出張者連絡先() {
        return this.出張者連絡先;
    }

    public void set出張者連絡先(java.lang.String 出張者連絡先) {
        this.出張者連絡先 = 出張者連絡先;
    }

    public ArrayList<Result> get結果() {
        return this.結果;
    }

    public void set結果(ArrayList<Result> 結果) {
        this.結果 = 結果;
    }

    public void set航空機を利用するか(java.lang.Boolean 航空機を利用するか) {
        this.航空機を利用するか = 航空機を利用するか;
    }

    public java.lang.Boolean get航空機を利用するか() {
        return this.航空機を利用するか;
    }

    public void set電車を利用するか(java.lang.Boolean 電車を利用するか) {
        this.電車を利用するか = 電車を利用するか;
    }

    public java.lang.Boolean get電車を利用するか() {
        return this.電車を利用するか;
    }

    public void set備考(java.lang.String 備考) {
        this.備考 = 備考;
    }

    public java.lang.String get備考() {
        return this.備考;
    }

    public ExportDocument(String 出張分類, String 資金種別,
                          Date 開始日, Date 終了日,
                          String 用務先事由,
                          String 定期始点, String 定期終点,
                          String 事業担当者所属, String 事業担当者教職員番号,
                          String 事業担当者職種, String 事業担当者氏名, String 事業担当者連絡先,
                          String 出張者所属, String 出張者教職員番号,
                          String 出張者職種, String 出張者氏名, String 出張者連絡先,
                          String 備考,
                          ArrayList<Result> 結果,
                          Boolean 航空機を利用するか, Boolean 電車を利用するか) {
        this.出張分類 = 出張分類;
        this.資金種別 = 資金種別;
        this.開始日 = 開始日;
        this.終了日 = 終了日;
        this.用務先事由 = 用務先事由;
        this.定期始点 = 定期始点;
        this.定期終点 = 定期終点;
        this.事業担当者所属 = 事業担当者所属;
        this.事業担当者教職員番号 = 事業担当者教職員番号;
        this.事業担当者職種 = 事業担当者職種;
        this.事業担当者氏名 = 事業担当者氏名;
        this.事業担当者連絡先 = 事業担当者連絡先;
        this.出張者所属 = 出張者所属;
        this.出張者教職員番号 = 出張者教職員番号;
        this.出張者職種 = 出張者職種;
        this.出張者氏名 = 出張者氏名;
        this.出張者連絡先 = 出張者連絡先;
        this.結果 = 結果;
        this.航空機を利用するか = 航空機を利用するか;
        this.電車を利用するか = 電車を利用するか;
        this.備考 = 備考;
    }

}
